"********************** Colors
syntax enable           " enable syntax processing
set background=dark     " background color (light/dark)
"colorscheme solarized  " color scheme
autocmd vimenter * ++nested colorscheme gruvbox

"********************** Spaces & Tabs
set tabstop=4           " number of visual spaces per TAB
set softtabstop=4       " number of spaces in tab when editing
set shiftwidth=4        " when indenting with '>', use 4 spaces width
set expandtab           " tabs are spaces
" do not expand tab for make files
autocmd FileType make set noexpandtab

"********************** UI Config
set number              " show line numbers
set showcmd             " show command in bottom bar
set cursorline          " highlight current line
filetype on
filetype indent on      " load filetype-specific indent files
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching braces/paranthesis
set ai                  " set autointending on
set ls=2                " show file name
set ruler               " always show the ruler
set colorcolumn=80      " insert a colorcolumn (for line limit)
set formatoptions+=r    " comment formatting

"********************** Solarized color
set t_Co=16
let g:solarized_termcolors=16

"********************** Terminal
set splitbelow          " all splits to happen below
set termwinsize=20x0
" open terminal by pressing Ctrl+m
nnoremap <silent><C-m> : bo term<CR>

"********************** Searching
set incsearch           " search as characters are entered
set hlsearch            " highlight matches
" turn off search highlight by pressing a space
nnoremap <silent><space> :nohlsearch<CR>

"********************** Pluggins Specific

"*********** NERDTree
" Start NERDTree and put the cursor back in the other window.
" autocmd VimEnter * NERDTree | wincmd p

" change default arrows
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

" toggle NERDTree by pressing Ctrl+e
nnoremap <silent><C-e> :NERDTreeToggle<CR>

"*********** vim-gitgutter
set updatetime=100      " diff markers should appear faster

"*********** tagbar
" toggle tabgbar by pressing Ctrl+b
nnoremap <silent><C-b> :TagbarToggle<CR>

"********************** Custom commands
" remove all trailing whitespace upon saving(:w) a file
autocmd BufWritePre * :%s/\s\+$//e

"********************** Advanced Colors
"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif
