#!/bin/bash
# display clock at the right top of the shell.
# clock contains date, time, git branch and return status of the last bash
# command

# colors for prompt
GREEN="\[$(tput setaf 2)\]"
BLUE="\[$(tput setaf 4)\]"
DEFAULT="\[$(tput sgr0)\]"

# git branch
function git_branch() {
  if git status > /dev/null 2>&1; then
      BRANCH="$(git branch | cut -b 3-)"
  else
    BRANCH=""
  fi
  echo $BRANCH
}

function prompt_command {
    STATUS=$?

    DATE=$(date +%a,\ %b\ %d\ %Y)
    TIME=$(date +%I:%M%P)
    GIT_BRANCH=$(git_branch)

    let PROMPT_X=$(tput cols)-17

    if [ $STATUS -eq 0 ]; then
        STATUS_STR="OK"
        STATUS_COLOR=4
    else
        STATUS_STR="ERROR($STATUS)"
        STATUS_COLOR=1
    fi

    # display the date
    tput sc
    tput cup 0 ${PROMPT_X}
    tput setaf 4
    echo -n $DATE
    tput setaf 2
    echo -n "|"

    # display the time
    tput cup 1 ${PROMPT_X}
    tput setaf 4
    printf "%16s" $TIME
    tput setaf 2
    echo -n "|"

    # display the git branch
    tput cup 2 ${PROMPT_X}
    tput setaf 4
    printf "%16s" $GIT_BRANCH
    tput setaf 2
    echo -n "|"

    # display the return status
    tput cup 3 ${PROMPT_X}
    tput setaf ${STATUS_COLOR}
    printf "%16s" $STATUS_STR
    tput setaf 2
    echo -n "|"
    tput rc

    PS1="${debian_chroot:+($debian_chroot)}${GREEN}\u@\h${DEFAULT}:${BLUE}\W${DEFAULT}\$ "
}

PROMPT_COMMAND=prompt_command
